### PR TITLE
uprev

### PR DESCRIPTION
**Pull request by eranrund**

### CODE REVIEW

**Review by garbageslam — APPROVED** [review]

**Comment by eranrund** [comment]
@garbageslam I piled in more changes, please take another look. I am going to deploy to k8 to ensure this still works.

**Review by jcape — APPROVED** [review]

**Comment by eranrund** [comment]
@jcape @garbageslam I pulled in some more commits into `mobilecoin` in case you want to take another look.

**Comment by eranrund** [comment]
Since this got bigger I am going to run it through k8 one more time.

**Comment by eranrund** [comment]
✅ k8 passed - https://deploybot.canadacentral.mobilecoin.com/blue/organizations/jenkins/mobilecoin-internal/detail/deploy%2Feran/193/pipeline/642

**Pull request merged**
